language:
    csharp 
sudo: required 
mono: none 
dotnet: 6.0 

os: - linux 

before_script: 
- dotnet restore ".\NinjaCollector.sln" 

script: 
- dotnet build ".\NinjaCollector.sln" -c Release 
- dotnet test ".\NinjaCollector.sln" -c Release -v n