version: '3.4'

services:
  storedb:
    ports:
      - "27017:27017"
  
  dbservice:
    container_name: DbService
    expose:
      - "14010:80"
      - "14011:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - storedb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  mainservice:
    container_name: NinjaCollector
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "14000:80"
      - "14001:443"
    depends_on:
      - dbservice
      - loggerservice
      - authservice
      - redditservice
      - telegramservice
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  loggerservice:
    container_name: LoggerService
    expose:
      - "14090:80"
      - "14091:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - dbservice
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  redditservice:
    container_name: RedditService
    env_file: reddit_settings.env
    expose:
      - "14030:80"
      - "14031:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - dbservice
      - loggerservice
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  authservice:
    container_name: AuthService
    env_file: auth.env
    expose:
      - "127.0.0.1:14020:80"
      - "127.0.0.1:14021:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - dbservice
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  telegramservice:
    container_name: TelegramService
    env_file: telegram.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    expose:
      - "14040:80"
      - "14041:443"
    depends_on:
      - dbservice
      - loggerservice
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
