version: '3.4'

services:

  storedb:
    image: mongo:6.0.3
    restart: always
    container_name: 'StoreDb'

  logDb:
    image: elasticsearch:8.5.3
    container_name: 'logDb'

  kibana:
    image: kibana:8.5.3
    container_name: 'kibana'
 
  dbservice:
    image: ${DOCKER_REGISTRY-}dbservice
    build:
      context: .
      dockerfile: DbService/Dockerfile

  mainservice:
    image: ${DOCKER_REGISTRY-}mainservice
    build:
      context: .
      dockerfile: MainService/Dockerfile

  loggerservice:
    image: ${DOCKER_REGISTRY-}loggerservice
    build:
      context: .
      dockerfile: LoggerService/Dockerfile

