version: '3.4'

services:

  storedb:
    image: mongo:6.0.3
    container_name: 'StoreDb'
 
  dbservice:
    image: ${DOCKER_REGISTRY-}dbservice
    build:
      context: .
      dockerfile: DbService/Dockerfile

  mainservice:
    image: ${DOCKER_REGISTRY-}mainservice
    build:
      context: .
      dockerfile: MainService/Dockerfile

  loggerservice:
    image: ${DOCKER_REGISTRY-}loggerservice
    build:
      context: .
      dockerfile: LoggerService/Dockerfile

  redditservice:
    image: ${DOCKER_REGISTRY-}redditservice
    build:
      context: .
      dockerfile: RedditService/Dockerfile

  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile

  telegramservice:
    image: ${DOCKER_REGISTRY-}telegramservice
    build:
      context: .
      dockerfile: TelegramService/Dockerfile

